### ISSUE TITLE
Users - Criação de CRUD

### ISSUE THREAD

**Issue by franciscognclvs** [mersonff/clicksign-hackaton#4]
Criar CRUD de Users:

- [ ] Criar model: name, email, password
- [ ] Criar controller: create, update, destroy
- [ ] Autenticação JWT: instalar gem e configurar
- [ ] Testes

**Comment by mersonff** [comment]
https://dev.to/adrianvalenz/authentication-with-sorcery-rspec-and-rails-7-building-a-simple-rails-cms-part-1-505c

**Comment by Hugo-NF** [comment]
https://github.com/Gokul595/api_guard
